LukeMathWalker/cargo-manifest

- Cargo.toml
- src/afs.rs
Make manifest construction deterministic.
The use of a `HashSet` when traversing directories was causing non-determinism when constructing the autobins and autotests. It has been switched for a `BtreeSet`.
I also enabled the `preserve_order` feature for the `toml` crate. Not sure if this is strictly necessary but it seemed a good idea.
> make manifest construction deterministic

- src/lib.rs
- tests/parse.rs
[`package.readme`][1] supports boolean values for suppressing the default `README` file lookup with `readme = false`, or defaulting to `README.md` with `readme = true`.
I've pretty much copied the implemention [from cargo itself][2], but with a derived `Deserialize` since the improved error message is probably not worth the manual impl.
Please let me know if you have any feedback! Thanks.
[1]: https://doc.rust-lang.org/cargo/reference/manifest.html#the-readme-field
[2]: https://github.com/rust-lang/cargo/blob/c524fa4e36b1b6134bf6d1fc17f0648f194118c7/src/cargo/util/toml/mod.rs#L715-L720
---
**Context:** I'm using `cargo-chef` as part of a workflow for cross-platform testing, and `cargo chef prepare` is failing with an error:
```
Error: Failed to compute recipe
Caused by:
0: invalid type: …
```
> Add support for boolean values in package.readme

- .github/workflows/general.yml
- tests/parse.rs
I have my editor set up to do this and noticed a couple of warnings while making #6. I figured I might as well turn on linting for tests in CI, in case it's something you think should be enabled! Thanks.
> Lint tests in CI

- src/lib.rs
- tests/autobuild/Cargo.toml
- tests/metadata/Cargo.toml
- tests/metadata/build.rs
- tests/parse.rs
With this, support for `build.rs` in `cargo chef` should be complete.
See LukeMathWalker/cargo-chef#44
---
This is required to prevent borrow checking errors in the next commit,
and I argue it is more logical this way - it no longer has to check that
self.package is Option::Some for example.
> Autodetect also build = "build.rs" field of [package]

- src/lib.rs
This fixes the current clippy error.
> Allow unnecessary wrap for deserialize_with fn

- src/lib.rs
- tests/parse.rs
Currently parsing of some attributes in the normal kebap-case fails (e.g. `proc-macro`).
This PR allows for deserialization of the normal kebap-case variants. When used for serialization now the kebap-case variant is used instead of the snake_case variant.
I am not sure, why you chose to `rename` some fields while `alias`ing the others in #4.
What do you think?
> snake-case: Alias instead of rename

- Cargo.toml
- src/lib.rs
- tests/parse.rs
Mark all fields in `DependencyDetail` as optional.
Ensure that table serialization works as expected by serializing tables last.
> [Breaking] Refine serialization

- src/error.rs
- src/lib.rs
This copies support for the `strip` parameter of profiles from upstream, to fix https://github.com/LukeMathWalker/cargo-chef/issues/149. I rebuilt cargo-chef with this change, and confirmed that it fixes the issue.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> Copy strip settings from upstream

- src/lib.rs
- tests/parse.rs
https://doc.rust-lang.org/cargo/reference/manifest.html#the-build-field says that valid values for the `build` field are paths and `false`, which basically matches the `readme` field (except for the workspace inheritance). Since `readme` uses the `StringOrBool` enum, it makes sense to use the same for the `build` field as well.
> Change `build` field to `Option<StringOrBool>`

- src/lib.rs
- tests/opt_level.toml
- tests/parse.rs
*Issue #, if available:* relevant issue in [cargo chef](https://github.com/LukeMathWalker/cargo-chef/issues/236)
*Description of changes:*
Added split-debuginfo to profiles.
I did not add `#[serde(alias = "split_debuginfo")]`. When I tried that with a `Cargo.toml`, it issued a warning about unused key. However, it issued the same warning for `overflow_checks` which have this alias. So I am not sure if even though there is the warning the alias are actually parsed or not. I'm saying this just in case the new field should have this attribute.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> Add split-debuginfo to cargo profiles

- src/lib.rs
see https://github.com/rust-lang/cargo/blob/b4ddf95ad9954118ac0dae835f2966394ad04c02/src/cargo/util/toml/mod.rs#L1400 and https://github.com/rust-lang/cargo/blob/b4ddf95ad9954118ac0dae835f2966394ad04c02/src/cargo/util/toml/mod.rs#L1424
> Package: Fix `default-run` naming

- src/lib.rs
A `Package` with only `name` and `version` set should only serialize these two fields, but currently it also serializes the additional `auto...` fields independent from their values. This PR changes the logic to only serialize these fields if they do not match the default value (`true` in this case).
An alternative is using `Option<bool>` for these fields, but that would be a breaking change, so I was a little hesitant about it.
It looks like `cargo-toml` is using similar logic: https://docs.rs/cargo_toml/0.16.0/src/cargo_toml/cargo_toml.rs.html#1262
> Skip serialization for `bool` fields if the value matches the default value

- src/lib.rs
- tests/serialize.rs
`Manifest` and `Package` are currently quite annoying to instantiate because all the fields need to be explicitly assigned even if only a small subset is used.
This PR implements the `Default` trait for the `Manifest` struct allowing an instantiation like `Manifest { package, ..Default::default() }`.
This PR also adds a `new()` fn to the `Package` struct for similar reasons. An alternative to this is implementing `Default` too, but that would leave us with `name: ""` and `version: ""`. I'm undecided which way feels better, but for `new()` there is [prior art](https://docs.rs/cargo_toml/0.16.0/cargo_toml/struct.Package.html#method.new).
Finally, this PR also adds a small serialization test case, to ensure that these API keep working in the future :)
<sub>By submitting this pull request, I …
> Make `Manifest` and `Package` easier to instantiate

- .github/workflows/general.yml
https://github.com/actions-rs/tarpaulin is apparently unmaintained and does not seems to work anymore. This PR changes the GitHub Actions workflow over to using essentially `cargo install cargo-tarpaulin` with some caching, and then running `cargo tarpaulin`. This should fix the failing CI jobs. :)
> CI: Fix `coverage` job

- src/lib.rs
- tests/snapshots/parse__default_features_casing.snap
- tests/snapshots/parse__opt_level.snap
- tests/snapshots/parse__workspace_dependency-2.snap
- tests/snapshots/parse__workspace_dependency.snap
`DependencyDetail` can have quite a few other fields, while with inheritance only `features` and `optional` are allowed (see https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace). Instead of having `Detailed` represent both cases, this change introduces a new `Inherited` variant specifically for the `{ workspace = true }` case.
> Dependency: Add `Inherited` variant

- Cargo.toml
- src/error.rs
The https://github.com/dtolnay/thiserror crate basically generates the same code, but requires much less boilerplate compared to implementing these impls manually. The downside would be that we're adding another dependency and potentially a small increase in compile time, but on the other hand it makes it much easier to add new custom error variants.
> Use `thiserror` crate to derive `Error` impls

- src/lib.rs
- tests/opt_version.toml
- tests/parse.rs
- tests/snapshots/parse__autobin.snap
- tests/snapshots/parse__autobuild.snap
- tests/snapshots/parse__autolib.snap
- tests/snapshots/parse__default_features_casing.snap
- tests/snapshots/parse__dev_dependencies_casing.snap
- tests/snapshots/parse__legacy-2.snap
- tests/snapshots/parse__legacy.snap
- tests/snapshots/parse__metadata.snap
- tests/snapshots/parse__opt_level.snap
- tests/snapshots/parse__opt_version.snap
- tests/snapshots/parse__package_inheritance.snap
- tests/snapshots/parse__proc_macro_casing-2.snap
- tests/snapshots/parse__proc_macro_casing.snap
- tests/snapshots/parse__workspace_dependency-2.snap
- a possibility from Cargo 1.75: https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-175-2023-12-28
*Description of changes:*
This would prepare for a subsequent fix in Cargo Chef of https://github.com/LukeMathWalker/cargo-chef/issues/265
> Package version can now be optional

- Cargo.toml
The field is an array, so we should use it like that... :D
> Fix `authors` field in `Cargo.toml`

- src/afs.rs
- src/lib.rs
This PR cleans up/improves some of the function arguments related to the `AbstractFileSystem` trait. See the individual commits for details on the changes :)
> afs: Adjust fn arguments

- src/lib.rs
- tests/snapshots/parse__autolib.snap
https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-crate-type-field specifies the default `crate-type` for libraries to be `lib` instead of `rlib`
> Adjust default `crate_type` for libraries

- src/lib.rs
- tests/snapshots/parse__autobin.snap
see https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-crate-type-field
If we set it for libraries (see https://github.com/LukeMathWalker/cargo-manifest/pull/36), then we should probably set it for other kinds of targets too.
> Set default `crate_type` for binaries, examples, tests, and benchmarks

- src/lib.rs
`file_names_in()` can fail in two relevant ways:
- If the requested folder does not exist it fails with a `NotFound` error. Since we are requesting `.` this cannot happen.
- If anything else IO-related fails we don't want to silently ignore it, instead we want to propagate that fact to the caller.
> Simplify `build.rs` lookup

- src/afs.rs
The `std::io::ErrorKind::NotFound` behavior wasn't properly described previously, so this PR adds a couple of doc comments to the trait and impl.
> AbstractFilesystem: Add doc comments

- src/lib.rs
This helps users discover the corresponding methods on the `Manifest` struct
> Add doc comments to `Package::auto*` fields

- Cargo.toml
This resolves the "yaml-rust is unmaintained" warning shown by cargo-deny.
> Update `insta` to v1.39.0

- src/lib.rs
- tests/autotarget.rs
- tests/parse.rs
- tests/snapshots/autotarget__full_example.snap
- tests/snapshots/autotarget__full_example_with_declarations_2015.snap
- tests/snapshots/autotarget__full_example_with_declarations_2021.snap
- tests/snapshots/autotarget__full_example_without_discovery.snap
This fixes the merging behavior of the auto-discovery code. Previously an explicit `[[bin]]` would turn off the auto-discovery unconditionally, but:
- in the 2018 edition the behavior was changed so that only `autobins = false` would disable the auto-discovery
- the auto-discovery information should still be used to fill in the `path` values
This PR changes the behavior to act accordingly. `cargo` shows errors in a couple of more situations (see tests), but the new implementation explicitly does not treat these as hard errors to be able to ignore broken target declarations in existing crates and turn them into warnings instead.
Resolves #35
/cc @kornelski
> Reimplement target auto-discovery

- src/lib.rs
- tests/autotarget.rs
If a `[[bin]]` for `src/main.rs` is explicitly declared with a different name than the crate the code would previously add two entries to the `bin` field of the `Manifest`. This commit fixes the discovery by only comparing the paths, but not the names of the discovered targets.
@LukeMathWalker if you're currently busy I'm happy merge and release this if you grant me the necessary permissions. also, congrats! 😉
> Fix duplicate `src/main.rs` discovery

- CHANGELOG.md
- Cargo.toml
- cliff.toml
This adds a changelog generated via https://git-cliff.org/
The changelog contains all pull requests labeled with `breaking`, `enhancement`, `bug`, `documentation` or `internal` and shows them in their corresponding groups.
The file can be regenerated via `git cliff -o`, assuming that a `GITHUB_TOKEN` environment variable has been set to allow unthrottled GitHub API access.
> Add release changelog

- README.md
- src/lib.rs
unfortunately the "note" block isn't rendered by rustdoc, but that could be addressed in a dedicated PR if anyone is annoyed enough by it :)
> Use `README.md` as module doc comment

- src/lib.rs
- tests/snapshots/parse__workspace_dependency.snap
[Docs on the Cargo manifest format](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-metadata-table) specify a metadata key for workspace manifests, that's completely ignored, but is still very useful for custom tools. This PR includes the optional workspace metadata in the `Workspace` type.
> Parse workspace metadata

- src/lib.rs
This is basically similar to the `Deserialize` implementation, but sometimes the stringification is useful outside of having to save it back to a TOML file :D
> Edition: Implement `as_str()` fn

- Cargo.toml
Thank you for your work on this crate! I particularly appreciate the ability to specify a custom `Metadata` type when reading a manifest.
This PR proposes to disable the unused `display` Cargo feature to slightly reduce compile time for users (which may be useful when using `cargo-manifest` from a proc-macro in the compilation critical path), see the commit message below.
---
The `display` Cargo feature of the `toml` dependency is only used for tests, so we disable it to reduce the effective size for users, and enable it only for tests.
For reference, the default features of `toml` are `display` and `parse`.
> toml: disable the unused `display` Cargo feature

- Cargo.lock
- Cargo.toml
see https://github.com/dtolnay/thiserror/releases/tag/2.0.0 :)
This shouldn't actually cause any visible differences to our users AFAICT
> Update `thiserror` dependency to v2

- src/lib.rs
> Support `package.resolver = "3"`, as shipped in Rust 1.84.0

- src/lib.rs
- tests/serialize.rs
The current Default implementation is limited to `Manifest<_, Value>`, because the impl of `Default` only specifies the first type parameter. This PR aims to fix that
> Fix impl Default for Manifest
